<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.openmarkov</groupId>
  <artifactId>org.openmarkov.learning.core</artifactId>
  <version>0.1.1</version>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.1.2</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>        
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
	<dependencies>
		<dependency>
			<groupId>org.openmarkov</groupId>
			<artifactId>org.openmarkov.core</artifactId>
			<version>0.1.1</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>release</id>
			<name>OpenMarkov</name>
			<url>http://openmarkov.org:8081/nexus/content/repositories/releases</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>snapshots</id>
			<name>OpenMarkov Snapshots</name>
			<url>http://openmarkov.org:8081/nexus/content/repositories/snapshots/</url>
			<layout>default</layout>
		</repository>
	</repositories>
	<distributionManagement>
		<repository>
			<uniqueVersion>false</uniqueVersion>
			<id>releases</id>
			<name>Releases</name>
			<url>http://openmarkov.org:8081/nexus/content/repositories/releases</url>
		</repository>
		<snapshotRepository>
			<uniqueVersion>true</uniqueVersion>
			<id>snapshots</id>
			<name>Snapshots</name>
			<url>http://openmarkov.org:8081/nexus/content/repositories/snapshots/</url>
		</snapshotRepository>
	</distributionManagement>    

</project>